<li><div class="box"><a href="javascript:;"><div class="img"><img src="//placeimg.com/300/300/any/1" alt=""></div></a></div></li>
<li><div class="box"><a href="javascript:;"><div class="img"><img src="//placeimg.com/300/300/any/2" alt=""></div></a></div></li>
<li><div class="box"><a href="javascript:;"><div class="img"><img src="//placeimg.com/300/300/any/3" alt=""></div></a></div></li>
<li><div class="box"><a href="javascript:;"><div class="img"><img src="//placeimg.com/300/300/any/4" alt=""></div></a></div></li>
<li><div class="box"><a href="javascript:;"><div class="img"><img src="//placeimg.com/300/300/any/5" alt=""></div></a></div></li>
<li><div class="box"><a href="javascript:;"><div class="img"><img src="//placeimg.com/300/300/any/6" alt=""></div></a></div></li>
<li><div class="box"><a href="javascript:;"><div class="img"><img src="//placeimg.com/300/300/any/7" alt=""></div></a></div></li>
<li><div class="box"><a href="javascript:;"><div class="img"><img src="//placeimg.com/300/300/any/8" alt=""></div></a></div></li>
<li><div class="box"><a href="javascript:;"><div class="img"><img src="//placeimg.com/300/300/any/9" alt=""></div></a></div></li>
<li><div class="box"><a href="javascript:;"><div class="img"><img src="//placeimg.com/300/300/any/10" alt=""></div></a></div></li>